version: '1.0.0'
services:
  backend:
    image: node:12-alpine
    working_dir: /app
    command: node index.js
    stop_signal: SIGKILL
    volumes:
      - ./backend:/app
    ports:
      - '4000:4000' # Expose API port to host
  frontend:
    image: node:12-alpine
    working_dir: /app
    command: npm start
    stop_signal: SIGKILL
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000' # Expose React default port to host